### ISSUE TITLE
https://tchspk.rs/cfp site down

### ISSUE THREAD

**Issue by therealpecus** [flaki/tchspk.rs#18]
Hi,

https://tchspk.rs/cfp has been down for a few days (I checked with isup.me to avoid local issues).
It seem the domain has not been renewed (Registration expiry date: 26.01.2019 10:07:42)

I like the service, it would be nice to see it going. If any help is required let me know.

TIA

**Comment by flaki** [comment]
Hi @therealpecus!

Indeed we had some domain-related issues but we are back up & running again ;)

Thank you for your kind words and watch out for some pretty cool announcements soon, we have some real treat in store for you all in the coming weeks! ;)
